### ISSUE TITLE
Newly deployed web instance is missing jschema.html

### ISSUE THREAD

**Issue by dsteckbeck** [DimDragon/jschema#1]
I'm getting a 404 for the file jschema.html . The browser seems to load up many other assets for the tool. When loading it from jschema.com, I don't see this file referenced anywhere, so are there additional steps i need to take to get the tool running on my own server?
The "Schema Validate About" links don't do anything, and the "By Input" and the gear icon don't do anything either. I'm not sure if the problem is related to the missing file...

![screenshot from 2015-12-04 13 51 51](https://cloud.githubusercontent.com/assets/2599452/11599757/41853d28-9a8e-11e5-9048-175b7b6ddf26.png)

**Comment by DimDragon** [comment]
@dsteckbeck can you check if you have the file in \scripts\jschema\jschema.html I see it is present in GitHub code so I wonder why it is missing for you. Can also try to access it directly in your case:
http://159.203.99.69/jschema/JSchema/scripts/jschema/jschema.html

If you look closely you will see it also loaded on jschema.com, this file contains all CSS for main rendering so it can't be skipped.

**Comment by DimDragon** [comment]
@dsteckbeck forget my previous comment. I see it is public URL so I tested myself. Problem seem to be the url case sensitivity. Your path like:

http://159.203.99.69/jschema/JSchema/scripts/jschema/jschema.html

works fine, but not:

http://159.203.99.69/jschema/JSchema/scripts/JSchema/jschema.html

I'm looking into it. Will let you know asap.

**Comment by DimDragon** [comment]
@dsteckbeck problem was in \scripts\jschema\jschema.js. I guess I only tested on case-insensitive setup in WebServer and never noticed that. Should be ok now, please just pull this file again and let me know if all is fine for you?

**Comment by dsteckbeck** [comment]
Still an error, its looking for:
   http://159.203.99.69/jschema/JSchema/scripts/JSchema/jschema.html
But the 2nd JSchema directory on disk is all lowercase, so it _should_ be looking for
   http://159.203.99.69/jschema/JSchema/scripts/jschema/jschema.html
unless you'd rather change the directory case...

**Comment by DimDragon** [comment]
are you taking master or development branch? I have only updated development at this point

**Comment by dsteckbeck** [comment]
I'm pretty sure I'm on development

```
[hros@hros JSchema]$ date
Fri Dec  4 16:00:12 EST 2015
[hros@hros JSchema]$ git pull 
remote: Counting objects: 6, done.
remote: Total 6 (delta 0), reused 0 (delta 0), pack-reused 6
Unpacking objects: 100% (6/6), done.
From https://github.com/DimDragon/jschema
   65d7f22..e559319  development -> origin/development
Already up-to-date.
```

**Comment by dsteckbeck** [comment]
@DimDragon nevermind... git status shows I'm on master

**Comment by dsteckbeck** [comment]
@DimDragon Bingo! The UI appears to be working now. Thanks for your assistance!

**Comment by DimDragon** [comment]
thanks for the update. I will also update master branch with this bug fix.
